esphome:
  name: XXXX_nodemcu_temphum_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "XXXX"
  password: "XXXX"
  manual_ip:
    # Set this to the IP of the ESP if cant get DHCP
    static_ip: 192.168.1.150
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "NodemcuX Fallback Hotspot"
    password: "XXXXXXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "XXXX"

ota:
  password: "XXXX"

sensor:
  - platform: dht
    pin: D6
    temperature:
      name: "XXXX Temperature"
    humidity:
      name: "XXXX Humidity"
    update_interval: 30s
    model: DHT11
